import { Transaction, Category } from "@/app/types";

export const CATEGORY_COLORS: Record<string, string> = {
  Salary: "#22d3ee",
  Freelance: "#38bdf8",
  Investment: "#34d399",
  "Food & Dining": "#f87171",
  Transport: "#fb923c",
  Shopping: "#c084fc",
  Healthcare: "#4ade80",
  Entertainment: "#fbbf24",
  Utilities: "#94a3b8",
  Rent: "#f472b6",
  Education: "#60a5fa",
  Other: "#64748b",
};

export const EXPENSE_CATEGORIES: Category[] = [
  "Food & Dining",
  "Transport",
  "Shopping",
  "Healthcare",
  "Entertainment",
  "Utilities",
  "Rent",
  "Education",
  "Other",
];

export const INCOME_CATEGORIES: Category[] = [
  "Salary",
  "Freelance",
  "Investment",
];

export const mockTransactions: Transaction[] = [
  // January
  {
    id: "t001",
    date: "2025-01-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t002",
    date: "2025-01-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t003",
    date: "2025-01-10",
    amount: 340,
    category: "Food & Dining",
    type: "expense",
    description: "Weekly groceries",
    merchant: "Whole Foods",
  },
  {
    id: "t004",
    date: "2025-01-12",
    amount: 850,
    category: "Freelance",
    type: "income",
    description: "UI design project",
    merchant: "Pixel Studio",
  },
  {
    id: "t005",
    date: "2025-01-15",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t006",
    date: "2025-01-18",
    amount: 210,
    category: "Shopping",
    type: "expense",
    description: "Clothing purchase",
    merchant: "Zara",
  },
  {
    id: "t007",
    date: "2025-01-20",
    amount: 65,
    category: "Entertainment",
    type: "expense",
    description: "Concert tickets",
    merchant: "Ticketmaster",
  },
  {
    id: "t008",
    date: "2025-01-22",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t009",
    date: "2025-01-28",
    amount: 300,
    category: "Investment",
    type: "income",
    description: "Dividend payment",
    merchant: "Vanguard",
  },
  {
    id: "t010",
    date: "2025-01-30",
    amount: 80,
    category: "Healthcare",
    type: "expense",
    description: "Pharmacy",
    merchant: "CVS Health",
  },

  // February
  {
    id: "t011",
    date: "2025-02-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t012",
    date: "2025-02-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t013",
    date: "2025-02-09",
    amount: 290,
    category: "Food & Dining",
    type: "expense",
    description: "Restaurant & groceries",
    merchant: "Various",
  },
  {
    id: "t014",
    date: "2025-02-14",
    amount: 180,
    category: "Shopping",
    type: "expense",
    description: "Valentine's gifts",
    merchant: "Amazon",
  },
  {
    id: "t015",
    date: "2025-02-16",
    amount: 1500,
    category: "Freelance",
    type: "income",
    description: "Web development project",
    merchant: "StartupXYZ",
  },
  {
    id: "t016",
    date: "2025-02-18",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t017",
    date: "2025-02-20",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t018",
    date: "2025-02-25",
    amount: 250,
    category: "Education",
    type: "expense",
    description: "Online course subscription",
    merchant: "Coursera",
  },

  // March
  {
    id: "t019",
    date: "2025-03-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t020",
    date: "2025-03-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t021",
    date: "2025-03-10",
    amount: 410,
    category: "Food & Dining",
    type: "expense",
    description: "Weekly groceries & dining",
    merchant: "Various",
  },
  {
    id: "t022",
    date: "2025-03-12",
    amount: 500,
    category: "Investment",
    type: "income",
    description: "Stock gains",
    merchant: "Robinhood",
  },
  {
    id: "t023",
    date: "2025-03-14",
    amount: 320,
    category: "Shopping",
    type: "expense",
    description: "Electronics accessories",
    merchant: "Best Buy",
  },
  {
    id: "t024",
    date: "2025-03-18",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t025",
    date: "2025-03-20",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t026",
    date: "2025-03-22",
    amount: 200,
    category: "Healthcare",
    type: "expense",
    description: "Doctor visit & lab tests",
    merchant: "City Medical Center",
  },
  {
    id: "t027",
    date: "2025-03-28",
    amount: 2000,
    category: "Freelance",
    type: "income",
    description: "Brand identity project",
    merchant: "Creative Agency",
  },

  // April
  {
    id: "t028",
    date: "2025-04-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t029",
    date: "2025-04-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t030",
    date: "2025-04-11",
    amount: 370,
    category: "Food & Dining",
    type: "expense",
    description: "Groceries & restaurants",
    merchant: "Various",
  },
  {
    id: "t031",
    date: "2025-04-15",
    amount: 700,
    category: "Investment",
    type: "income",
    description: "ETF dividends",
    merchant: "Fidelity",
  },
  {
    id: "t032",
    date: "2025-04-18",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t033",
    date: "2025-04-20",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t034",
    date: "2025-04-23",
    amount: 480,
    category: "Shopping",
    type: "expense",
    description: "Spring wardrobe",
    merchant: "H&M",
  },
  {
    id: "t035",
    date: "2025-04-27",
    amount: 120,
    category: "Entertainment",
    type: "expense",
    description: "Streaming & gaming",
    merchant: "Various",
  },

  // May
  {
    id: "t036",
    date: "2025-05-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t037",
    date: "2025-05-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t038",
    date: "2025-05-10",
    amount: 1200,
    category: "Freelance",
    type: "income",
    description: "Logo design project",
    merchant: "Startup Labs",
  },
  {
    id: "t039",
    date: "2025-05-13",
    amount: 350,
    category: "Food & Dining",
    type: "expense",
    description: "Groceries & dining",
    merchant: "Various",
  },
  {
    id: "t040",
    date: "2025-05-18",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t041",
    date: "2025-05-20",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t042",
    date: "2025-05-24",
    amount: 380,
    category: "Education",
    type: "expense",
    description: "Tech conference ticket",
    merchant: "TechConf 2024",
  },
  {
    id: "t043",
    date: "2025-05-28",
    amount: 900,
    category: "Investment",
    type: "income",
    description: "Crypto portfolio gains",
    merchant: "Coinbase",
  },

  // June
  {
    id: "t044",
    date: "2025-06-05",
    amount: 5800,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
    merchant: "TechCorp Inc.",
  },
  {
    id: "t045",
    date: "2025-06-07",
    amount: 1200,
    category: "Rent",
    type: "expense",
    description: "Monthly rent payment",
    merchant: "Urban Apartments",
  },
  {
    id: "t046",
    date: "2025-06-10",
    amount: 430,
    category: "Food & Dining",
    type: "expense",
    description: "Summer dining out",
    merchant: "Various",
  },
  {
    id: "t047",
    date: "2025-06-14",
    amount: 600,
    category: "Shopping",
    type: "expense",
    description: "Summer shopping",
    merchant: "Various",
  },
  {
    id: "t048",
    date: "2025-06-18",
    amount: 95,
    category: "Transport",
    type: "expense",
    description: "Monthly transit pass",
    merchant: "City Transit",
  },
  {
    id: "t049",
    date: "2025-06-20",
    amount: 145,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
    merchant: "Power & Grid Co.",
  },
  {
    id: "t050",
    date: "2025-06-22",
    amount: 1800,
    category: "Freelance",
    type: "income",
    description: "React app development",
    merchant: "FinanceCo",
  },
  {
    id: "t051",
    date: "2025-06-28",
    amount: 240,
    category: "Entertainment",
    type: "expense",
    description: "Music festival tickets",
    merchant: "Coachella",
  },
];